export const fila1=[
    {
        id:1,
        estado:"Libre",
        total:"",
        pago:"efectivo"
    },
    {
        id:2,
        estado:"Ocupado",
        total:"",
        pago:"efectivo"
    },
    {
        id:3,
        estado:"Libre",
        total:"",
        pago:"efectivo"
    },
    {
        id:4,
        estado:"Libre",
        total:"",
        pago:"efectivo"
    },
    {
        id:5,
        estado:"Libre",
        total:"",
        pago:"efectivo"
    },
    {
        id:6,
        estado:"Libre",
        total:"",
        pago:"efectivo"
    }
]

